import { z } from "zod";

const publicEnvSchema = z.object({
  NEXT_PUBLIC_SITE_URL: z.string().min(1),
  NEXT_PUBLIC_APP_STORE_URL: z.string().min(1),
  NEXT_PUBLIC_GOOGLE_PLAY_URL: z.string().min(1),
  NEXT_PUBLIC_CALENDLY_URL: z.string().min(1),
  NEXT_PUBLIC_TAAP_IT_DESKTOP_URL: z.string().min(1),
  NEXT_PUBLIC_TAAP_IT_MOBILE_URL: z.string().min(1),
  NEXT_PUBLIC_CEO_LINKEDIN_URL: z.string().min(1),
});

const parsed = publicEnvSchema.parse({
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_APP_STORE_URL: process.env.NEXT_PUBLIC_APP_STORE_URL,
  NEXT_PUBLIC_GOOGLE_PLAY_URL: process.env.NEXT_PUBLIC_GOOGLE_PLAY_URL,
  NEXT_PUBLIC_CALENDLY_URL: process.env.NEXT_PUBLIC_CALENDLY_URL,
  NEXT_PUBLIC_TAAP_IT_DESKTOP_URL: process.env.NEXT_PUBLIC_TAAP_IT_DESKTOP_URL,
  NEXT_PUBLIC_TAAP_IT_MOBILE_URL: process.env.NEXT_PUBLIC_TAAP_IT_MOBILE_URL,
  NEXT_PUBLIC_CEO_LINKEDIN_URL: process.env.NEXT_PUBLIC_CEO_LINKEDIN_URL,
});

export const publicEnv = {
  SITE_URL: parsed.NEXT_PUBLIC_SITE_URL,
  APP_STORE_URL: parsed.NEXT_PUBLIC_APP_STORE_URL,
  GOOGLE_PLAY_URL: parsed.NEXT_PUBLIC_GOOGLE_PLAY_URL,
  CALENDLY_URL: parsed.NEXT_PUBLIC_CALENDLY_URL,
  TAAP_IT_DESKTOP_URL: parsed.NEXT_PUBLIC_TAAP_IT_DESKTOP_URL,
  TAAP_IT_MOBILE_URL: parsed.NEXT_PUBLIC_TAAP_IT_MOBILE_URL,
  CEO_LINKEDIN_URL: parsed.NEXT_PUBLIC_CEO_LINKEDIN_URL,
} as const;
