# fly.toml app configuration file generated for vagabond-data-scraper-dev on 2026-01-03T23:50:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vagabond-data-scraper-dev'
primary_region = 'cdg'

[build]
  dockerfile = 'apps/data-scraper/Dockerfile'
  build-context = '.'
  build-target = 'data-scraper'

[http_service]
  internal_port = 3234
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
