packages:
  - "apps/*"
  - "libs/*"

catalog:
  # Core utilities
  dayjs: ^1.11.13
  zod: ^3.23.8
  ajv: ^8.17.1
  ajv-formats: ^3.0.1
  ajv-errors: ^3.0.0
  ajv-keywords: ^5.1.0
  "typebox": ^1.0.77
  dotenv: ^16.4.5

  #Database
  drizzle-orm: ^0.45.0
  drizzle-kit: ^0.31.8
  pg: ^8.13.1
  "@types/pg": ^8.11.11

  # Geospatial utilities
  geojson: ^0.5.0
  geolib: ^3.3.4
  "@types/geojson": ^7946.0.14
  "@types/geolib": ^2.0.3
  "@turf/turf": ^7.2.0

  # Build tools
  typescript: ^5.9.2

  # Code quality
  eslint: ^9.39.2
  "@eslint/js": ^9.39.2
  eslint-config-expo: ^10.0.0
  eslint-config-next: ^16.0.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-i18next: ^6.1.3
  eslint-plugin-prettier: ^5.5.5
  eslint-plugin-react-you-might-not-need-an-effect: ^0.8.5
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-tailwindcss: ^3.18.2
  typescript-eslint: ^8.55.0
  prettier: ^3.3.3

  # Node types
  "@types/node": ^22.9.0

  # React
  react: 19.1.0
  react-dom: 19.1.0
