version: "3.8"

services:
  # Service data-scraper
  data-scraper:
    build:
      context: ../..
      dockerfile: apps/data-scraper/Dockerfile
      target: data-scraper
    container_name: vagabond-data-scraper
    # Expose le port 3234 du conteneur vers le port 3234 de l'hôte
    ports:
      - "3234:3234"
    environment:
      BASIC_AUTH_USER: "user"
      BASIC_AUTH_PASSWORD: "password"
