import { Type } from "typebox";

/**
 * ⚠️ IMPORTANT: LIMITATION GEMINI JSON SCHEMA ⚠️
 *
 * Gemini ne supporte PAS plus d'environ 100 valeurs dans l'enum Gemini rejette le JSON schema
 * Gemini ne supporte PAS les valeurs d'enum dépassant 26 caractères dans son JSON Schema
 */

/**
 * Restaurant POI category values
 */
export const POI_RESTAURANT_CATEGORY_VALUES = [
  "afghan_restaurant",
  "afghani_restaurant",
  "african_restaurant",
  "alsace_restaurant",
  "american_restaurant",
  "angler_fish_restaurant",
  "arab_restaurant",
  "argentinian_restaurant",
  "armenian_restaurant",
  "asian_fusion_restaurant",
  "asian_restaurant",
  "australian_restaurant",
  "austrian_restaurant",
  "bangladeshi_restaurant",
  "barbecue_restaurant",
  "basque_restaurant",
  "belgian_restaurant",
  "biryani_restaurant",
  "box_lunch_restaurant",
  "brazilian_restaurant",
  "breakfast_restaurant",
  "british_restaurant",
  "brunch_restaurant",
  "buffet_restaurant",
  "bulgarian_restaurant",
  "burmese_restaurant",
  "burrito_restaurant",
  "cajun_restaurant",
  "californian_restaurant",
  "cambodian_restaurant",
  "canadian_restaurant",
  "cantonese_restaurant",
  "cape_verdean_restaurant",
  "caribbean_restaurant",
  "castilian_restaurant",
  "central_usa_restaurant",
  "cheesesteak_restaurant",
  "chicken_restaurant",
  "chicken_wings_restaurant",
  "chilean_restaurant",
  "chinese_noodle_restaurant",
  "chinese_restaurant",
  "chophouse_restaurant",
  "colombian_restaurant",
  "louisiana_restaurant",
  "continental_restaurant",
  "costa_rican_restaurant",
  "country_food_restaurant",
  "creole_restaurant",
  "cuban_restaurant",
  "czech_restaurant",
  "dance_restaurant",
  "danish_restaurant",
  "delivery_restaurant",
  "dessert_restaurant",
  "dim_sum_restaurant",
  "dojo_restaurant",
  "dominican_restaurant",
  "doner_kebab_restaurant",
  "dumpling_restaurant",
  "dutch_restaurant",
  "east_african_restaurant",
  "eastern_europe_restaurant",
  "eclectic_restaurant",
  "ecuadorian_restaurant",
  "egyptian_restaurant",
  "english_restaurant",
  "eritrean_restaurant",
  "ethiopian_restaurant",
  "ethnic_restaurant",
  "european_restaurant",
  "falafel_restaurant",
  "family_restaurant",
  "fast_food_restaurant",
  "filipino_restaurant",
  "fine_dining_restaurant",
  "fish_&_chips_restaurant",
  "fish_restaurant",
  "floridian_restaurant",
  "fondue_restaurant",
  "franconian_restaurant",
  "french_restaurant",
  "french_steak_restaurant",
  "fugu_restaurant",
  "fujian_restaurant",
  "fusion_restaurant",
  "georgian_restaurant",
  "german_restaurant",
  "gluten-free_restaurant",
  "greek_restaurant",
  "guatemalan_restaurant",
  "gyro_restaurant",
  "haitian_restaurant",
  "hakka_restaurant",
  "halal_restaurant",
  "hamburger_restaurant",
  "haute_french_restaurant",
  "hawaiian_restaurant",
  "health_food_restaurant",
  "hoagie_restaurant",
  "honduran_restaurant",
  "hong_kong_restaurant",
  "hot_dog_restaurant",
  "hot_pot_restaurant",
  "hunan_restaurant",
  "hungarian_restaurant",
  "indian_muslim_restaurant",
  "indian_restaurant",
  "indonesian_restaurant",
  "irish_restaurant",
  "israeli_restaurant",
  "italian_restaurant",
  "izakaya_restaurant",
  "jamaican_restaurant",
  "japanese_curry_restaurant",
  "japanese_restaurant",
  "japanese_sweets_restaurant",
  "jewish_restaurant",
  "korean_barbecue_restaurant",
  "korean_beef_restaurant",
  "korean_restaurant",
  "kosher_restaurant",
  "laotian_restaurant",
  "latin_american_restaurant",
  "lebanese_restaurant",
  "lithuanian_restaurant",
  "lunch_restaurant",
  "malaysian_restaurant",
  "mandarin_restaurant",
  "meat_dish_restaurant",
  "mediterranean_restaurant",
  "mexican_restaurant",
  "mexican_torta_restaurant",
  "mid-atlantic_restaurant_us",
  "middle_eastern_restaurant",
  "modern_british_restaurant",
  "modern_european_restaurant",
  "modern_french_restaurant",
  "modern_indian_restaurant",
  "modern_izakaya_restaurant",
  "mongolian_bbq_restaurant",
  "moroccan_restaurant",
  "native_american_restaurant",
  "neapolitan_restaurant",
  "nepalese_restaurant",
  "new_american_restaurant",
  "new_england_restaurant",
  "new_zealand_restaurant",
  "nicaraguan_restaurant",
  "north_african_restaurant",
  "north_indian_restaurant",
  "north_italian_restaurant",
  "norwegian_restaurant",
  "nuevo_latino_restaurant",
  "oaxacan_restaurant",
  "organic_restaurant",
  "oyster_bar_restaurant",
  "pacific_rim_restaurant",
  "pakistani_restaurant",
  "pan-asian_restaurant",
  "pan-latin_restaurant",
  "pancake_restaurant",
  "persian_restaurant",
  "peruvian_restaurant",
  "pho_restaurant",
  "pizza_restaurant",
  "polish_restaurant",
  "polynesian_restaurant",
  "portuguese_restaurant",
  "po_boys_restaurant",
  "puerto_rican_restaurant",
  "punjabi_restaurant",
  "raclette_restaurant",
  "ramen_restaurant",
  "raw_food_restaurant",
  "restaurant",
  "restaurant_or_cafe",
  "rice_restaurant",
  "roman_restaurant",
  "romanian_restaurant",
  "russian_restaurant",
  "salvadoran_restaurant",
  "satay_restaurant",
  "scandinavian_restaurant",
  "seafood_donburi_restaurant",
  "seafood_restaurant",
  "serbian_restaurant",
  "sfiha_restaurant",
  "shabu-shabu_restaurant",
  "shanghainese_restaurant",
  "shawarma_restaurant",
  "sichuan_restaurant",
  "sicilian_restaurant",
  "singaporean_restaurant",
  "small_plates_restaurant",
  "soul_food_restaurant",
  "soup_restaurant",
  "south_african_restaurant",
  "south_american_restaurant",
  "south_asian_restaurant",
  "south_indian_restaurant",
  "southeast_asian_restaurant",
  "south_italian_restaurant",
  "southern_restaurant_us",
  "southwestern_restaurant_us",
  "spanish_restaurant",
  "sri_lankan_restaurant",
  "steamboat_restaurant",
  "sundae_restaurant",
  "suppon_restaurant",
  "sushi_restaurant",
  "swedish_restaurant",
  "swiss_restaurant",
  "syrian_restaurant",
  "taco_restaurant",
  "taiwanese_restaurant",
  "takeout_restaurant",
  "tapas_restaurant",
  "tempura_restaurant",
  "teppanyaki_restaurant",
  "tex-mex_restaurant",
  "thai_restaurant",
  "tibetan_restaurant",
  "tofu_restaurant",
  "tonkatsu_restaurant",
  "trad_american_restaurant",
  "traditional_restaurant",
  "tunisian_restaurant",
  "turkish_restaurant",
  "tuscan_restaurant",
  "udon_noodle_restaurant",
  "ukrainian_restaurant",
  "unagi_restaurant",
  "uruguayan_restaurant",
  "uzbeki_restaurant",
  "vegan_restaurant",
  "vegetarian_restaurant",
  "venezuelan_restaurant",
  "vietnamese_restaurant",
  "west_african_restaurant",
  "western_restaurant",
  "wok_restaurant",
  "yakiniku_restaurant",
  "yakitori_restaurant",
  "yemeni_restaurant",
  "yemenite_restaurant",
  "yucatan_restaurant",
  "zhejiang_restaurant",
] as const;

/**
 * Religious POI category values
 */
export const POI_RELIGIOUS_CATEGORY_VALUES = [
  "abundant_life_church",
  "alliance_church",
  "anglican_church",
  "apostolic_church",
  "armenian_church",
  "assemblies_of_god_church",
  "baptist_church",
  "buddhist_temple",
  "calvary_chapel_church",
  "cathedral",
  "catholic_cathedral",
  "catholic_church",
  "christian_church",
  "church",
  "church_of_christ",
  "church_latter_day_saints",
  "church_of_the_nazarene",
  "city_pillar_shrine",
  "conservative_synagogue",
  "deaf_church",
  "disciples_of_christ_church",
  "eastern_orthodox_church",
  "episcopal_church",
  "evangelical_church",
  "foursquare_church",
  "friends_church",
  "full_gospel_church",
  "gospel_church",
  "greek_orthodox_church",
  "hindu_temple",
  "hispanic_church",
  "jain_temple",
  "korean_church",
  "lutheran_church",
  "mennonite_church",
  "messianic_synagogue",
  "methodist_church",
  "moravian_church",
  "mosque",
  "new_age_church",
  "non-denominational_church",
  "orthodox_church",
  "orthodox_synagogue",
  "parsi_temple",
  "pentecostal_church",
  "presbyterian_church",
  "protestant_church",
  "quaker_church",
  "reform_synagogue",
  "reformed_church",
  "russian_orthodox_church",
  "seven-day_adventist_church",
  "shinto_shrine",
  "shrine",
  "synagogue",
  "taoist_temple",
  "unitarian_church",
  "united_church_of_christ",
  "united_methodist_church",
  "unity_church",
  "vineyard_church",
  "wesleyan_church",
] as const;

/**
 * Entertainment and recreation POI category values
 */
export const POI_ENTERTAINMENT_CATEGORY_VALUES = [
  "adult_entertainment",
  "adult_entertainment_club",
  "amateur_theater",
  "amphitheater",
  "amusement_center",
  "amusement_park",
  "amusement_park_ride",
  "attraction",
  "ballet_theater",
  "casino",
  "children_amusement_center",
  "childrens_theater",
  "concert_hall",
  "drama_theater",
  "drive-in_movie_theater",
  "entertainment",
  "entertainment_recreation",
  "imax_theater",
  "karaoke_bar",
  "movie_theater",
  "opera_house",
  "outdoor_movie_theater",
  "performing_arts_theater",
  "puppet_theater",
  "theater_production",
  "theme_park",
  "water_park",
] as const;

/**
 * Museum and cultural POI category values
 */
export const POI_MUSEUM_CULTURAL_CATEGORY_VALUES = [
  "archaeological_museum",
  "archaeological_site",
  "army_museum",
  "art_center",
  "art_gallery",
  "art_handcraft",
  "art_museum",
  "artistic_handicrafts",
  "artwork",
  "bouncy_castle_hire",
  "castle",
  "children_museum",
  "cultural_landmark",
  "dart_bar",
  "ethnographic_museum",
  "fortress",
  "handicraft_museum",
  "heritage_museum",
  "historic_city_center",
  "historical_landmark",
  "historical_place",
  "historical_place_museum",
  "historical_society",
  "history_museum",
  "landmark",
  "local_history_museum",
  "maritime_museum",
  "memorial",
  "memorial_estate",
  "memorial_park",
  "modern_art_museum",
  "monument",
  "museum",
  "museum_of_space_history",
  "museum_of_zoology",
  "national_museum",
  "natural_history_museum",
  "open_air_museum",
  "rail_museum",
  "ruin",
  "science_museum",
  "sculpture",
  "sculpture_museum",
  "space_of_remembrance",
  "statue",
  "technology_museum",
  "tower",
  "toy_museum",
  "war_memorial",
  "war_museum",
  "wax_museum",
] as const;

/**
 * Natural and outdoor POI category values
 */
export const POI_NATURAL_OUTDOOR_CATEGORY_VALUES = [
  "animal_park",
  "aquarium",
  "beach",
  "beach_pavillion",
  "biking_trail",
  "botanical_garden",
  "cave",
  "city_park",
  "community_garden",
  "country_park",
  "dog_park",
  "garden",
  "hiking_area",
  "island",
  "lake",
  "mountain_pass",
  "mountain_peak",
  "mountain_range",
  "national_forest",
  "national_park",
  "park",
  "river",
  "river_confluence",
  "scenic_spot",
  "seasonal_lake",
  "state_park",
  "trail_head",
  "viewpoint",
  "waterfall",
  "wildlife_and_safari_park",
  "wildlife_park",
  "zoo",
] as const;

/**
 * Accommodation POI category values
 */
export const POI_ACCOMMODATION_CATEGORY_VALUES = [
  "campground",
  "camping_cabin",
  "camping_farm",
  "capsule_hotel",
  "cottage_rental",
  "cottage_village",
  "dinner_theater",
  "dog_hostel",
  "extended_stay_hotel",
  "guest_house",
  "health_resort",
  "hostel",
  "hot_spring_hotel",
  "hotel",
  "inn",
  "lodge",
  "love_hotel",
  "motel",
  "mountain_cabin",
  "resort",
  "resort_hotel",
  "ski_resort",
  "travellers_lodge",
  "wellness_hotel",
  "working_womens_hostel",
  "youth_hostel",
] as const;

/**
 * Shopping and market POI category values
 */
export const POI_SHOPPING_MARKET_CATEGORY_VALUES = [
  "antique_restoration_store",
  "antique_furniture_store",
  "antique_store",
  "cheese_shop",
  "chinese_supermarket",
  "chocolate_shop",
  "clothes_market",
  "discount_supermarket",
  "farmers_market",
  "gift_basket_store",
  "gift_shop",
  "hypermarket",
  "ice_cream_shop",
  "industrial_supermarket",
  "market",
  "outlet_mall",
  "pastry_shop",
  "souvenir_store",
  "supermarket",
  "wedding_souvenir_shop",
] as const;

/**
 * Transport and infrastructure POI category values
 */
export const POI_TRANSPORT_INFRASTRUCTURE_CATEGORY_VALUES = [
  "airport_parking_lot",
  "bridge",
  "free_parking_lot",
  "learn_driver_training_area",
  "marina",
  "mountain_cable_car",
  "park_&_ride",
  "parking",
  "parking_garage",
  "parking_lot",
  "parking_lot_for_bicycles",
  "parking_lot_motorcycles",
  "public_parking_lot",
  "public_parking_space",
  "public_transport",
  "river_port",
  "sports_bar",
  "tsukigime_parking_lot",
] as const;

/**
 * Services and business POI category values
 */
export const POI_SERVICES_BUSINESS_CATEGORY_VALUES = [
  "aerospace_company",
  "agricultural_cooperative",
  "agriculture_cooperative",
  "amusement_machine_supplier",
  "amusement_ride_supplier",
  "arena",
  "auto_market",
  "auto_parts_market",
  "bar_&_grill",
  "bar_pmu",
  "bar_stool_supplier",
  "bar_tabac",
  "bariatric_surgeon",
  "bark_supplier",
  "barrel_supplier",
  "barrister",
  "book_publisher",
  "building_materials_market",
  "business_park",
  "cattle_market",
  "public_accountant",
  "chamber_of_handicrafts",
  "cheese_manufacturer",
  "chocolate_artisan",
  "chocolate_factory",
  "christmas_market",
  "cinema_equipment_supplier",
  "city_dept_public_safety",
  "city_gate",
  "city_walls",
  "clothing_wholesale_market",
  "coffee_machine_supplier",
  "coffee_roasters",
  "coffee_stand",
  "coffee_store",
  "coffee_vending_machine",
  "coffee_wholesaler",
  "coin_operated_locker",
  "cooperative",
  "corporate_gift_supplier",
  "cottage",
  "coworking_space",
  "dept_of_public_safety",
  "eyebrow_bar",
  "fixed-base_operator",
  "flea_market",
  "floating_market",
  "flower_market",
  "fountain",
  "fresh_food_market",
  "garden_building_supplier",
  "garden_center",
  "garden_machinery_supplier",
  "gardener",
  "gay_bar",
  "gift_wrap_store",
  "girl_bar",
  "government",
  "handicraft",
  "handicraft_exporter",
  "handicraft_fair",
  "head_start_center",
  "home_cinema_installation",
  "housing_cooperative",
  "makerspace",
  "market_operator",
  "market_researcher",
  "marketing",
  "mobile_network_operator",
  "monument_maker",
  "music_publisher",
  "new_years_tree_market",
  "newspaper_publisher",
  "night_market",
  "notary_public",
  "olive_oil_cooperative",
  "opera_company",
  "port_operating_company",
  "printed_music_publisher",
  "produce_market",
  "public_school",
  "public_health_department",
  "public_housing",
  "public_library",
  "public_medical_center",
  "public_relations_firm",
  "public_utility",
  "public_works_department",
  "publisher",
  "seafood_market",
  "souvenir_manufacturer",
  "stand_bar",
  "tea_market_place",
  "technology_park",
  "theater_company",
  "tour_operator",
  "town_hall",
  "traditional_market",
  "vegetable_wholesale_market",
  "wholesale_market",
] as const;

/**
 * Food and drink (non-restaurant) POI category values
 */
export const POI_FOOD_DRINK_CATEGORY_VALUES = [
  "army_barracks",
  "art_cafe",
  "bar",
  "barbecue_area",
  "beer_garden",
  "bistro",
  "brasserie",
  "brewery",
  "brewpub",
  "cabaret_club",
  "cafe",
  "cafeteria",
  "childrens_cafe",
  "chocolate_cafe",
  "cider_bar",
  "cocktail_bar",
  "coffee_shop",
  "comic_cafe",
  "cosplay_cafe",
  "distillery",
  "dog_cafe",
  "espresso_bar",
  "gastropub",
  "hookah_bar",
  "internet_cafe",
  "irish_pub",
  "live_music_bar",
  "military_barracks",
  "piano_bar",
  "poke_bar",
  "pub",
  "public_amenity_house",
  "public_bath",
  "public_bathroom",
  "public_beach",
  "public_female_bathroom",
  "public_golf_course",
  "public_male_bathroom",
  "public_swimming_pool",
  "public_webcam",
  "public_wheelchair_bathroom",
  "sake_brewery",
  "salsa_bar",
  "snack_bar",
  "super_public_bath",
  "tapas_bar",
  "tiki_bar",
  "vegetarian_cafe_and_deli",
  "wine_bar",
  "winery",
] as const;

/**
 * Sports and fitness POI category values
 */
export const POI_SPORTS_FITNESS_CATEGORY_VALUES = [
  "athletic_park",
  "beach_volleyball_club",
  "beach_volleyball_court",
  "bmx_park",
  "bowling_alley",
  "bowling_club",
  "cycling_park",
  "day_spa",
  "ecological_park",
  "facial_spa",
  "fish_spa",
  "fishing_lake",
  "greyhound_stadium",
  "health_spa",
  "holiday_park",
  "hot_bedstone_spa",
  "massage_spa",
  "medical_spa",
  "mobile_home_park",
  "mountaineering_class",
  "nudist_park",
  "parkour_spot",
  "rv_park",
  "skateboard_park",
  "spa",
  "spa_and_health_club",
  "spa_garden",
  "spa_town",
  "stadium",
  "swimming_lake",
] as const;

export const POI_GAMIFIED_CATEGORIES = [
  // --- RELIGION (Détaillé pour la collection) ---
  "cathedral", // Cathédrales, basiliques et grandes églises historiques
  "church", // Églises paroissiales, chapelles et églises de toutes dénominations chrétiennes
  "monastery_abbey", // Abbayes, monastères, couvents et lieux de vie monastique
  "mosque", // Mosquées et centres culturels islamiques
  "synagogue", // Synagogues et lieux de culte juifs
  "temple_buddhist", // Temples bouddhistes et pagodes
  "temple_hindu_jain", // Temples hindous et jaïns
  "temple_taoist_shinto", // Temples taoïstes et sanctuaires Shinto
  "shrine_altar", // Petits sanctuaires, autels, sites de pèlerinage et shrines
  "religious_misc", // Autres lieux de culte et sites spirituels divers

  // --- PATRIMOINE & ARCHITECTURE (Inclus tes types obligatoires) ---
  "castle_fortress", // Châteaux (castle), forteresses, forts (fort) et palais
  "historic_monument", // Statues, monuments, mémoriaux (memorial) et fontaines (fountain)
  "historic_landmark", // Mairies (townhall), portes de ville (city_gate), remparts (citywalls) et ponts (bridge)
  "archaeological_site", // Ruines, sites de fouilles et vestiges antiques
  "heritage_building", // Bâtiments classés, patrimoine architectural général (tags yes, building, heritage)

  // --- CULTURE & ARTS ---
  "museum_art", // Musées des beaux-arts, galeries et artwork en intérieur
  "museum_history", // Musées d'histoire, d'archéologie et musées militaires
  "museum_science", // Musées des sciences, d'histoire naturelle et technologie
  "museum_specialized", // Musées thématiques (jouets, artisanat, insolite)
  "performing_arts", // Théâtres (theatre), opéras, salles de concert et cabarets

  // --- NATURE & PAYSAGES ---
  "viewpoint_tower", // Points de vue, panoramas, belvédères et tours d'observation (tower)
  "zoo_aquarium", // Parcs zoologiques (zoo), aquariums et parcs animaliers
  "botanical_garden", // Jardins botaniques, arboretums et serres
  "park_nature", // Parcs urbains, parcs nationaux et jardins publics
  "waterfall_cave", // Cascades, grottes et formations géologiques
  "lake_river", // Lacs, rivières, confluences et cours d'eau
  "mountain_peak", // Sommets, cols de montagne et zones de haute altitude
  "beach_marina", // Plages, fronts de mer et ports de plaisance (marina)
  "hiking_trail", // Sentiers de randonnée et parcours de marche

  // --- LOISIRS & VIE LOCALE ---
  "amusement_park", // Parcs à thèmes, parcs aquatiques et centres de loisirs
  "winery_brewery", // Vignobles, brasseries, distilleries et routes des vins
  "market_local", // Marchés (market), halles, marchés aux puces et de Noël
  "spa_wellness", // Spas, centres thermaux et bien-être
  "stadium_sports", // Stades, arènes et complexes sportifs majeurs
  "shopping_district", // Centres commerciaux, quartiers artisanaux et boutiques de souvenirs
  "nightlife_casino", // Casinos, vie nocturne et divertissements pour adultes
  "cinema_entertainment", // Cinémas et centres de divertissement numérique

  // --- GASTRONOMIE ---
  "restaurant", // Cuisine locale, gastronomie et bistrots
  "cafe_bakery", // Cafés, salons de thé et pâtisseries artisanales
  "bar_pub", // Bars, pubs et brasseries de quartier

  // --- SERVICES TOURISTIQUES ---
  "tourist_service", // Offices de tourisme, info points et tours opérateurs
  "accommodation", // Hôtels, campings et hébergements touristiques
] as const;

/**
 * All POI category values combined
 */
export const POI_CATEGORY_VALUES = [
  // ...POI_RESTAURANT_CATEGORY_VALUES,
  // ...POI_RELIGIOUS_CATEGORY_VALUES,
  // ...POI_ENTERTAINMENT_CATEGORY_VALUES,
  // ...POI_MUSEUM_CULTURAL_CATEGORY_VALUES,
  // ...POI_NATURAL_OUTDOOR_CATEGORY_VALUES,
  // ...POI_ACCOMMODATION_CATEGORY_VALUES,
  // ...POI_SHOPPING_MARKET_CATEGORY_VALUES,
  // ...POI_TRANSPORT_INFRASTRUCTURE_CATEGORY_VALUES,
  // ...POI_SERVICES_BUSINESS_CATEGORY_VALUES,
  // ...POI_FOOD_DRINK_CATEGORY_VALUES,
  // ...POI_SPORTS_FITNESS_CATEGORY_VALUES,
  ...POI_GAMIFIED_CATEGORIES,
] as const;

// ALL CATEGORIES length: 683

export const PoiCategoryTypesSchema = Type.Enum(POI_CATEGORY_VALUES, {
  description: "Categories or tags associated with the POI",
  type: "string",
  $id: "PoiCategoryTypes",
});
