version: '3.8'
name: vagabond-api
services:
  db:
    container_name: postgresql-postgis
    image: postgis/postgis:16-3.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vagabond
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  minio-s3:
    container_name: minio-s3
    image: minio/minio:latest
    volumes:
      - s3-data:/data
    ports:
      - "9321:9000"
      - "9322:9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data

  create-minio-buckets:
    container_name: create-minio-buckets
    image: minio/mc:latest
    depends_on:
      - minio-s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio-s3:9000 user password;
      /usr/bin/mc mb myminio/local-vagabond-s3-bucket;
      /usr/bin/mc anonymous set public myminio/local-vagabond-s3-bucket;
      exit 0;
      "
volumes:
  db-data:
  s3-data:

networks:
  backend:
    driver: bridge
